task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('tasks.urls')),
    path('task-api/', include('tasks.api.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

tasks/urls.py
from django.urls import path

from . import views

app_name = 'tasks'
urlpatterns = [
    path('', views.UserCreationsView.as_view(), name='user-create'),
    path('create-task/', views.TaskCreate.as_view(), name='task-create'),
    path('account-login/', views.UserLogin.as_view(), name='login-user'),
    path('logout/', views.userLogout, name='logout-user'),
    path('user-task-list/', views.UserTaskListView.as_view(), name='task-list'),
    path('user-task-list-filter/', views.TaskFilterView.as_view(), name='task-list-filter'),
    path('user-task-search/', views.TaskSearchView.as_view(), name='task-search'),
    path('task-details/<int:pk>/', views.TaskDetailsView.as_view(), name='task-details'),
    path('delete-task/<int:pk>/', views.DeleteTask.as_view(), name='task-delete'),
    path('update-task-view/<int:pk>/', views.TaskUpdate.as_view(), name='task-update-view'),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> {% block title %}  {% endblock title %} </title>
</head>
<body>

    <h1>
        {% if  request.user.is_authenticated %}
        
        {{ request.user.first_name }} {{ request.user.last_name }} | |   
        
        <a href="{% url 'tasks:task-create' %}"> Add New Task </a>  | |


        <a href="{% url 'tasks:task-list' %}"> Task List </a>  | |

        <a href="{% url 'tasks:logout-user' %}"> Logout </a>  

        {% else %}
            <a href="{% url 'tasks:login-user' %}"> Login </a>  | |      
            <a href="{% url 'tasks:user-create' %}"> Registration </a>      
        {% endif %}
    </h1>
    <hr><hr>
    
    {% block content %}  
   
    
    {% endblock content %}

</body>
</html>

templates/create_task.html
{% extends "base.html" %}

{% block title %} Task Create  {% endblock title %}



{% block content %}  

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <form action="{% url 'tasks:task-create' %}" method="post" enctype="multipart/form-data">
        {% csrf_token %}
        
        Title: <input type="text" name="title" id="" placeholder="Title"  required> <br><br>
        Description:  <textarea rows="5" cols="33" name="description" placeholder="Description" required></textarea> <br><br>
      Images:  <input type="file" name="image" id="" multiple="true" accept="image/*" required> <br><br>
       Due Date: <input type="date" name="dueDate" id="" required> <br><br>
        <input type="checkbox" id="vehicle1" name="isComplete" value="True"> 
        <label for="vehicle1"> Is Complete</label><br><br>
        <label for="priority" >Priority:</label>
        <select name="priority" id="">
            <option value="Low">Low</option>
            <option value="Medium">Medium</option>
            <option value="High">High</option>
        </select> <br> <br>
        <button type="submit">Create</button>

    </form>

{% endblock content %}

templates/create_user.html
{% extends "base.html" %}

{% block title %} Create User Account  {% endblock title %}



{% block content %}  

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <form action="{% url 'tasks:user-create' %}" method="post">
        {% csrf_token %}

        {% for field in form %}
    <div class="fieldWrapper">
        {{ field.errors }}
        {{ field.label_tag }} {{ field }}
        {% if field.help_text %}
        <p class="help">{{ field.help_text|safe }}</p>
        {% endif %}
    </div>
{% endfor %}

        <br><br>
        <button type="submit">Create</button>

    </form>

{% endblock content %}

templates/login_user.html
{% extends "base.html" %}

{% block title %} Login  {% endblock title %}

{% block content %}  


    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <form action="{% url 'tasks:login-user' %}" method="post">
        {% csrf_token %}

        Username <input type="username" name="username" id="username" required value="{{ username }}"> <br>
        Password <input type="password" name="password" id="password" required value="{{ password }}"> <br><br>
    
        <button type="submit">Login</button>

    </form>

{% endblock content %}

templates/task_details.html
{% extends "base.html" %}

{% block title %} Task Details  {% endblock title %}


{% block content %}  

{% if task %}

    <p>
        <h3>Title:</h3>
    {{ task.title }}
    </p>

    <h3>Description:</h3> 
    {{ task.description }}

    <h3>Images:</h3>
    <p>
        {% for image in task.images.all %}
        <img src="{{ image.image.url }}" alt="{{ image.image}}" srcset="" width="200" > <br> <hr><hr>
        {% endfor %}
    </p>

    <h3>Created At:</h3>
    {{ task.creationDateTime }}
    <h3>Task Priority:  </h3>
    {{ task.priority }}
   <h3> Task Due Date: </h3>
   {{ task.dueDate }}
    <h3>
    {% if task.isCompleted %} 
        Task Completed
     {% else %}
         Task Incomplete.
    {% endif %}
    </h3>
    <br> <br>

    <a href="{% url 'tasks:task-update-view' task.id %}" > Update Task </a><br> <br>
    <a href="{% url 'tasks:task-delete' task.id %}" > Delete Task </a><br> <br>

{% else %}
    <h2>You have no permission to access this task.</h2>

{% endif %}


{% endblock content %}

templates/task_update.html
{% extends "base.html" %}

{% block title %} Task Update  {% endblock title %}

{% block content %}  

<form action="" method="post">
    {% csrf_token %}

    {{ form.as_p }}

    <button type="submit">Update</button>
</form>


{% endblock content %}

templates/user_task_list.html
{% extends "base.html" %}

{% block title %} Task List  {% endblock title %}


{% block content %}

    <form action="{% url 'tasks:task-list-filter' %}" method="get">
        <label for="status" >Status:</label>
        <select name="status" id="">
            <option value="True">Completed</option>
            <option value="False">Incomplete</option>
        </select> 
        <label for="priority" >Priority:</label>
        <select name="priority" id="">
            <option value="Low">Low</option>
            <option value="Medium">Medium</option>
            <option value="High">High</option>
        </select> 

        <button type="submit">Filter</button>
    </form>
    
   <br><br><br>

    <form action="{% url 'tasks:task-search' %}" method="get">

        <input type="text" name="title" id="" placeholder="Title" required>
        <button type="submit">Search</button>
    </form>

    <hr><hr>

    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}


    {% for task in user_task_list %}
       <h2>{{ task.title }}</h2> 
        {{ task.description|truncatewords:"10" }} <a href="{% url 'tasks:task-details' task.id %}" > Read More  </a><br>
        <hr>
        {% empty %}
           <h2> No tasks available. </h2>
    {% endfor %}

{% endblock content %}